### PR TITLE
fix imports and test latest compilers

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
Oh, that triggered a bug in cairoD or dmd-2.067.0.

**Comment by BlackEdder** [comment]
Thanks @MartinNowak . Have you tried debugging the error in more detail, or would you like me to take a closer look.

**Comment by MartinNowak** [comment]
Yes, I reduced it to a compiler bug.
[Issue 14443 – [Reg 2.067.0] Incorrect double freeing of reference counted struct](https://issues.dlang.org/show_bug.cgi?id=14443)
It's a bit unfortunate, because it happens in a unittest of cairoD, not in plotd itself.

**Comment by BlackEdder** [comment]
This bug was fixed in 2.068. Thanks @MartinNowak!

**Pull request merged**
